### ISSUE TITLE
Credit Hope Adoli for his design work for the project

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#105]
His site: https://www.linkedin.com/in/hopeadoli/
Figma: https://www.figma.com/file/8l6vGwioDjBZm0rpbCmBYh/Design?type=design&node-id=185%3A146&mode=design&t=qUWrptaY7kuJVD1f-1

References #96

**Comment by sabderemane** [comment]
Related #106

**Comment by sarahboyce** [comment]
Also done 💪
