### ISSUE TITLE
Update landing page 

### ISSUE THREAD

**Issue by sabderemane** [djangonaut-space/wagtail-indymeet#106]
Update the landing page with Hope design
![Desktop](https://github.com/djangonaut-space/wagtail-indymeet/assets/17890338/ac62ccb2-82cc-42ca-a741-7e28abc71000)

This is a mockup, wording will be replaced by what we have currently (or something else if we want)

**Comment by sarahboyce** [comment]
Let's also update the page title and manifest icons when we do this to not be the default
![image](https://github.com/djangonaut-space/wagtail-indymeet/assets/42296566/dbc008d2-427f-4fa2-9d2d-d8f16f8454e2)

**Comment by sarahboyce** [comment]
I think this is done! Great job ⭐
