### ISSUE TITLE
Create a discord channel that relays all djangonaut social media posts

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#116]
This should make it easier for folks to keep track of new conversations, retoot, republish, reshare and generally engage with.

**Comment by sarahboyce** [comment]
(Note: I am going to post manually untill we automate)

**Comment by tim-schilling** [comment]
We can do this with a premium subscription to mee6 setting up a RSS feed for https://indieweb.social/@djangonaut.rss

**Comment by tim-schilling** [comment]
I did this for free with ReadyBot. https://readybot.io/bots/14694/edit
