### ISSUE TITLE
Create a page for sponsors and partners - community and financial

### ISSUE THREAD

**Issue by sarahboyce** [djangonaut-space/wagtail-indymeet#117]
This requires some discussion but probably a page with sponsors per year
Partners and thank yous can give recognition to other supportive groups (Django News, Django Chat, PyLadies etc)

This is to track we want something on the website

Lowish priority

**Comment by tim-schilling** [comment]
Anyone who helped us with our advertising should also be on the list.

- Adam Johnson
- Brian Okken
- Django Chat / Will Vincent
- Jack Linke
- Mark Walker / django-cms

**Comment by dawnwages** [comment]
Need to update the GeneralPage functionality that is almost available on staging. Assigning this to myself first.

**Comment by dawnwages** [comment]
https://staging-djangonaut-space.azurewebsites.net/sponsors-and-partners/
Sorted!

Also ran into a whole host of other bugs deploying this so I'm glad its all done.

**Comment by tim-schilling** [comment]
Need to add sentry to this list

**Comment by RachellCalhoun** [comment]
https://djangonaut.space/partnerships-sponsors/
For the first iteration this could be "complete" until we decide on sponsor levels and we then can format/order it a bit more with that in mind.

For this page, to include links in images I had to use raw html block. I also created a new ticket to make this a feature going forward : https://github.com/djangonaut-space/wagtail-indymeet/issues/372
