### ISSUE TITLE
models

### ISSUE THREAD

**Issue by dawnwages** [Djangonaut-Space/wagtail-indymeet#12]
on going discussion on how to set this up:

- [ ] Person
- Name
- Pronouns
- Image
- description
- links Many-to-Many Links
- email
- newsletter **are they participating in the cohort / receiving emails**
- created_at

- [ ] Links
- name
- url

- [ ] Events
- speakers many to many Person
- cover image
- category
- date
- time
- status (in case we cancel or reschedule? not convinced we need this)
- description
- created_at
- RSVP many-to-many Person

- [ ] Lists
- people many to many to Person
- description
- created_at

**Comment by dawnwages** [comment]
https://pypi.org/project/wagtail-eventcalendar/

**Comment by RachellCalhoun** [comment]
https://github.com/code4recovery/wagtail-meeting-guide

**Comment by dawnwages** [comment]
great minds think alike!

**Comment by dawnwages** [comment]
We've done this and think it's great!
