### ISSUE TITLE
Update STORAGES default backend for production for permanent file storage

### ISSUE THREAD

**Issue by sarahboyce** [djangonaut-space/wagtail-indymeet#123]
We probably want to use django-staorages (and as we are using Azure use their azure integration: https://django-storages.readthedocs.io/en/latest/backends/azure.html)
Our `Event.cover_image` is currently uploaded to disk and is vulnerable to being wiped during the deployment process

**Comment by dawnwages** [comment]
Sorted in this PR: https://github.com/djangonaut-space/wagtail-indymeet/pull/137
