### ISSUE TITLE
Add Azure App Insights

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#124]
Occasionally builds will fail and result in the web app no longer serving our content. Instead it's the Azure placeholder page. The github action says it was successful. The only way to determine this has occurred is to browse to the site and see that it's rendering an unexpected page.

I imagine there's some logs in Azure somewhere that contain the information about what's happening.

**Comment by dawnwages** [comment]
https://opentelemetry.io/docs/
https://opentelemetry-python.readthedocs.io/en/latest/index.html can do!

**Comment by dawnwages** [comment]
> https://opentelemetry.io/docs/ https://opentelemetry-python.readthedocs.io/en/latest/index.html can do!

I think we're going to go with App Insights instead.

**Comment by dawnwages** [comment]
#114 Duplicate issue

**Comment by tim-schilling** [comment]
@dawnwages I think the core part of this issue was lost at some point. The problem was that the builds fail sporadically and in the worst cases it will end up serving the Azure placeholder page rather than any version of our application. I can see how having additional logging would help in debugging this situation, but the focus here was on the robustness of our infrastructure.

**Comment by dawnwages** [comment]
Closed with the opening of #114 and upgrading P1 of Azure.
