### ISSUE TITLE
Document process to add new environment variables

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#127]
I'm unsure of how to add new environment variables for our staging and production environments. This blocks me from being able to address other issues such as #114. I suspect the process already exists, it just need to learn what it is.

**Comment by dawnwages** [comment]
Here's a video!
https://drive.google.com/file/d/1pUXEZO-msJWPgKyM8pQF5RIcFEAUBklO/view?usp=drive_link

Let me know if there's anything else you need.

**Comment by tim-schilling** [comment]
Thanks @dawnwages. Could we summarize the steps as:

1. Add [new repository secret](https://github.com/djangonaut-space/wagtail-indymeet/settings/secrets/actions) to our GitHub repo
2. Add environment variable to the relevant deployment [GitHub action workflows](https://github.com/djangonaut-space/wagtail-indymeet/tree/main/.github/workflows
) 
3. [Trigger build](https://github.com/djangonaut-space/wagtail-indymeet/actions/workflows/main_djangonaut-space.yml) for the correct platform via GitHub action
