### ISSUE TITLE
Move ugly notes to Proposal link

### ISSUE THREAD

**Issue by dawnwages** [Djangonaut-Space/wagtail-indymeet#20]
Notes: https://docs.google.com/document/d/1MD_WWt_E7BjFPvYQFqC7rxtOoz6lXMohnfhNc7FHVUc/edit

Proposal: https://docs.google.com/document/d/1jlg2sXuBTCUcNo0z05QlPAFwilDDnwEjgajAMF7aNHo/edit#

**Comment by dawnwages** [comment]
How much money will it cost? How much should we ask for?

**Comment by dawnwages** [comment]
Ask PSF and DSF?

**Comment by RachellCalhoun** [comment]
We should add the costs for hosting, domain etc to this doc as well.

**Comment by dawnwages** [comment]
Blocker #22 Azure Deploy

on Azure I think it will be ~60 USD/month ? I might be able to get Microsoft to donate that and it might end up cheaper if I use the right plans. Right now I'm shooting for staging, prod and a mail service. TBD

djangonaut.space on namecheap ~9 USD/year
<img width="533" alt="image" src="https://user-images.githubusercontent.com/20374042/210433388-a2fe9008-271c-4c06-9ee2-965500d69745.png">

<img width="551" alt="image" src="https://user-images.githubusercontent.com/20374042/210434044-8a9f77a2-36c9-4195-8483-52be4d4b6f52.png">

**Comment by dawnwages** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/20374042/211050495-a79dd994-a61a-4108-b5d1-4d0387985810.png">
