### ISSUE TITLE
Djangonaut.Space Logo and Motto

### ISSUE THREAD

**Issue by dawnwages** [djangonaut-space/wagtail-indymeet#23]
"Helping django professionals lift off!" < work in progress

**Comment by dawnwages** [comment]
![Image](https://user-images.githubusercontent.com/20374042/202747463-4ef104b9-22dc-4c72-af5c-7babac519e11.png)

**Comment by dawnwages** [comment]
use the "dj" of django inside the rocket

**Comment by RachellCalhoun** [comment]
@dawnwages  i think this is done?

**Comment by dawnwages** [comment]
Where contributors launch!
