### ISSUE TITLE
Add Sentry or Rollbar

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#243]
It's a bit difficult to see errors come through in the logs. Let's set up an error monitoring service like [Sentry](sentry.io/) or [Rollbar](rollbar.com).

**Comment by dawnwages** [comment]
This could be covered in #114 please confirm? Seems like duplicate issue.

**Comment by tim-schilling** [comment]
I believe these are different issues. Sentry and rollbar provides detailed error reports. Uptime robot tells us when the site is unexpectedly down.
