### ISSUE TITLE
Fix preview in wagtail

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#244]
The preview option in wagtail isn't working.

**Comment by dawnwages** [comment]
fixed: https://staging-djangonaut-space.azurewebsites.net/admin/pages/7/edit/

<img width="959" alt="image" src="https://github.com/djangonaut-space/wagtail-indymeet/assets/20374042/8f93391f-cfb7-48d5-ba03-cafea2715475">
