### ISSUE TITLE
Database backups

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#246]
This is a placeholder. I'm not sure if we have them automatically. It's probably worth investigating before we start accepting user sign ups.

**Comment by dawnwages** [comment]
We do have it automatically.
production:
<img width="656" alt="image" src="https://github.com/djangonaut-space/wagtail-indymeet/assets/20374042/db7a617f-a223-4eb8-96a8-9727d99da147">
staging: 
<img width="631" alt="image" src="https://github.com/djangonaut-space/wagtail-indymeet/assets/20374042/ef03f053-bde4-472e-ac58-de42e5dc25c5">

Mentioned in the djangonaut dot com documentation: https://docs.google.com/document/d/1T47kDAkVUQ_yC89y9RZ049KRskvNiObA_YGiIsnBWeY/edit?pli=1#heading=h.1afi41uioo3j

**Comment by tim-schilling** [comment]
I wonder if we could export one of those every month for long-term storage.

**Comment by RachellCalhoun** [comment]
> I wonder if we could export one of those every month for long-term storage.
I think it's a good idea as long as it's secure. Especially as we start scaling up.
