### ISSUE TITLE
Add pre-commit installation instructions to contributing docs

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#310]
Our project supports [pre-commit](https://pre-commit.com/#install), but fails to tell a contributor to actually install it.

**Comment by sarahboyce** [comment]
I think we have an issue that: 
- our pip files and currently deployed version needs python version 3.9
- our Readme says we use 3.10
- our pre-commit needs 3.11

Relates to: https://github.com/djangonaut-space/wagtail-indymeet/issues/200

It's a fairly poor local development experience with the different python versions.
Would love us to prioritize the Python upgrade 👍

**Comment by shreyash2002** [comment]
Hey @tim-schilling I am currently a beginner in python and django. I would like to contribute to this issue

**Comment by tim-schilling** [comment]
Excellent, thank you for your help!

**Comment by tim-schilling** [comment]
Completed in #393
