### ISSUE TITLE
Set up Black/Flake formatting

### ISSUE THREAD

**Issue by RachellCalhoun** [djangonaut-space/wagtail-indymeet#33]
Now that we have black and flake in the project, we should run these processes on a clean branch, and add in either manual or automated process to trigger these events after work is done on a new branch and before merging.

**Comment by dawnwages** [comment]
Also adding ruff

**Comment by sarahboyce** [comment]
This was completed recently: https://github.com/djangonaut-space/wagtail-indymeet/issues/339
