### ISSUE TITLE
Talwind build error due to !important

### ISSUE THREAD

**Issue by MHLut** [djangonaut-space/wagtail-indymeet#338]
The `manage.py tailwind build` command fails with the following error:

```sh
CssSyntaxError: /Users/mhlut/Webserver/wagtail-indymeet/theme/static_src/src/djangonaut-space.css:68:101: Unknown word
    at Input.error (/Users/mhlut/Webserver/wagtail-indymeet/theme/static_src/node_modules/postcss/lib/input.js:106:16)
```

This error originates from the keyword `#{!important}` in `@apply`, under the `.social-link` selector. Remove the former, and the error disappears.

According to https://github.com/tailwindlabs/tailwindcss/discussions/10799, you can apply the [Tailwind important modifier](https://tailwindcss.com/docs/configuration#important-modifier) to the relevant utility instead.

The important tag was added a couple of days ago for #327, but I can't see why it's needed. The style seems OK on localhost. Can we remove it again?

**Comment by RachellCalhoun** [comment]
Good catch! I also ran into this yesterday but forgot to followup 😅 . Thanks! @sarahboyce might have more insight. I think we definitely need to change/remove it.

**Comment by tim-schilling** [comment]
I think it's because without it the social media icons weren't showing up. They were all purple.

**Comment by MHLut** [comment]
> I think it's because without it the social media icons weren't showing up. They were all purple.

I think that one actually got fixed in the next PR that Sarah merged shortly after, which is #328.

**Comment by tim-schilling** [comment]
If that's the case, then it can likely be removed.

**Comment by sarahboyce** [comment]
I don't think I've properly fixed it still but yes you can remove the `#{!important}` 👍
