### ISSUE TITLE
Disable email warning when using Session.application_url

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#391]
The warning "Your email is not confirmed! You may not be able to apply for sessions without [confirming your email address.](https://djangonaut.space/accounts/profile/)" is being displayed despite the application is going to be through Google Forms via `Session.application_url`

We should remove this to avoid confusion before next Tuesday.

**Comment by sarahboyce** [comment]
This is only if you're logged in and still true for future sessions. They should confirm their email regardless and they still see the apply button in the case it's an external link
I think this is fine 🤷‍♀️

**Comment by tim-schilling** [comment]
Oh, that makes sense.
