### ISSUE TITLE
📺  Adds YouTube channel to footer on landing page

### ISSUE THREAD

**Issue by jefftriplett** [djangonaut-space/wagtail-indymeet#421]
I noticed you have a YouTube channel, but it's hard to find on the website. Would it make sense to add the channel to the footer? 

https://www.youtube.com/@djangonautspace

**Comment by tim-schilling** [comment]
Thanks for calling this out. We do have it on the non-landing page footer.

![image](https://github.com/user-attachments/assets/57d7ee38-9b20-4dfd-abd8-cf43be7e9137)

**Comment by jefftriplett** [comment]
Thank you! Good point. I updated the title of the issue, but everything else still applies.
