### ISSUE TITLE
localhost/rsvp/ part one

### ISSUE THREAD

**Issue by dawnwages** [djangonaut-space/wagtail-indymeet#5]
Part one:
- [ ] Form:
- Full name
- email
- capatcha
- agree to receive communications
- [ ] email confirmation to sender
- [ ] success message / failure message
![image](https://user-images.githubusercontent.com/20374042/200899274-baaae8b4-d1d3-44c8-b777-370ef6487693.png)
![image](https://user-images.githubusercontent.com/20374042/200899330-86170b20-474a-496b-9bd2-5d07b392e13c.png)

**Comment by RachellCalhoun** [comment]
Can non members RSVP? I think we might have a different set up from the example so we might need to adjust the form a bit.

**Comment by dawnwages** [comment]
This may be a duplicate of another issue.

**Comment by dawnwages** [comment]
- May need to sign in first to register

**Comment by RachellCalhoun** [comment]
I think this is mostly taken care of but we will need to add : 
agree to receive communications (when they sign up) 
email confirmation to sender (when they RSVP for an event)

**Comment by RachellCalhoun** [comment]
Closing this in favor of #13 to continue work there.
