### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by dawnwages** [djangonaut-space/wagtail-indymeet#65]
While we're working on the homepage, can we have a "coming soon" page just with sign up?

we are now live at djangonaut.space --  we could open the sign up for registration.

Pros:
- It will help us figure out resources if we get people in timezones we don't have covered
- We don't waste the opportunity to get people connected while we're still developing

Cons:
- random sign  ups
- too big of a first session

**Comment by tim-schilling** [comment]
Closed by #78
