### ISSUE TITLE
localhost/:event_categort:/:event_name:/

### ISSUE THREAD

**Issue by dawnwages** [djangonaut-space/wagtail-indymeet#7]
- [ ] Pop up or separate page for individual event
- [ ] Event name
- [ ] Event date
- [ ] Event time (do we want to use machine time zone or keep it a particular US time)
- [ ] Event description
- [ ] Add to agenda button
- [ ] Speakers list - name, pronouns, description, contact links, image
![image](https://user-images.githubusercontent.com/20374042/200900703-f4802dd0-0268-40b7-afaa-d58b84c038eb.png)

**Comment by RachellCalhoun** [comment]
closed by https://github.com/djangonaut-space/wagtail-indymeet/pull/42
