### ISSUE TITLE
Generic Unsubscribe links

### ISSUE THREAD

**Issue by RachellCalhoun** [djangonaut-space/wagtail-indymeet#74]
we need links to put in emails for unsubscribing from newsletters and events. 

this will also need URLS/views to update the user profile preferences. 

Also, include this link in all relevant.

**Comment by sarahboyce** [comment]
Going to close and say superseded by https://github.com/djangonaut-space/wagtail-indymeet/issues/307 
We have the generic link which unsubscribes them from everything, we need to update this to a confirmation page where the user can select which updates they want to unsubscibe from and save 👍
