### ISSUE TITLE
Code of Conduct 

### ISSUE THREAD

**Issue by dawnwages** [djangonaut-space/wagtail-indymeet#9]
- [ ] Code of Conduct for contribution
- [x] Code of Conduct for events

**Comment by RachellCalhoun** [comment]
https://www.djangoproject.com/conduct/

**Comment by RachellCalhoun** [comment]
This is on [our wiki](https://github.com/dawnwages/wagtail-indymeet/wiki/Code-of-Conduct), but it's a general. we might need to add more for contributing ..or maybe that's a "best practices" /"contributing expectations" doc.

**Comment by dawnwages** [comment]
do it like djangocon us

- repo - https://github.com/djangocon/2023.djangocon.us/blob/main/CODE_OF_CONDUCT.md
- website - CoC
- wiki

**Comment by dawnwages** [comment]
or include in .github directory
