### ISSUE TITLE
Use a unique uuid field for Event URLS

### ISSUE THREAD

**Issue by RachellCalhoun** [djangonaut-space/wagtail-indymeet#91]
Point for the future: If we introduce private events we may want to use a unique uuid field for this url. I'm not sure how protective we need to be of pending and cancelled events being potentially visible.

_Originally posted by @tim-schilling in https://github.com/djangonaut-space/wagtail-indymeet/pull/75#discussion_r1262479200_

**Comment by tim-schilling** [comment]
Or a `SlugField` that has some human readable text. It depends on our needs.

**Comment by tim-schilling** [comment]
This was completed.
