### ISSUE TITLE
Plausible for site traffic

### ISSUE THREAD

**Issue by dawnwages** [djangonaut-space/wagtail-indymeet#93]
https://plausible.io/open-source-website-analytics
research cost and add to budget.

**Comment by dawnwages** [comment]
Also open to other alternatives that are open source and friendly.

**Comment by sabderemane** [comment]
I have this one for my personal use, I recommend it ✅

**Comment by dawnwages** [comment]
If you'd like to set it up, feel free to grab the ticket. @sabderemane
